//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public string KID { get; set; }
        public string Klasa { get; set; }
        public string LID_FK { get; set; }
        public string JMBG_FK { get; set; }
    
        public virtual Let Let { get; set; }
        public virtual Putnik Putnik { get; set; }
    }
}
