//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public string JMBG { get; set; }
        public string ImPrz { get; set; }
    
        public virtual Putnik Putnik { get; set; }
        public virtual Radnik Radnik { get; set; }
    }
}
