//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze
{
    using System;
    using System.Collections.Generic;
    using EntityFramework.Triggers;
    using System.Windows;

    public partial class Radnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radnik()
        {
            this.Let = new HashSet<Let>();
            this.Obavestenje = new HashSet<Obavestenje>(); 
            Triggers<Radnik>.Inserted += e =>
            {
                throw new Exception("IMAMO DOVOLJNO ZAPOSLENIH!");
            };
        }

        public string JMBG { get; set; }
        public string ImPrz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Let> Let { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavestenje> Obavestenje { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Pilot Pilot { get; set; }
    }
}
