//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upravljati
    {
        public string AID { get; set; }
        public string JMBG { get; set; }
        public string UID { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Pilot Pilot { get; set; }
    }
}
